### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by MAleemH** [roniy68/recipe-app#12]
- There are two members: @roniy68 and @MAleemH 
- Click [here](https://github.com/roniy68/recipe-app/projects/1) to open our Github Project

**Comment by Munsa1** [comment]
Hi @MAleemH @roniy68, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes In Issue #10 :heavy_check_mark: 


## Optional suggestions
## Important :red_circle: 
- [ ] Kindly do not close Pull Requests or Issues submitted for review before approval. Its good practice to make the required change and re submit the same link for re-review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
